---
- name: distribute ssh private keys
  hosts: all
  tasks:
    - name: debug key path
      ansible.builtin.debug:
        msg: "{{ key_path }}"

    - name: Copy key
      ansible.builtin.copy:
        src: "{{ key_path }}"
        dest: "/home/{{ ansible_user }}/.ssh/id_rsa"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
